# Generated by Django 4.2.4 on 2023-08-23 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0002_account_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instructor",
            options={},
        ),
        migrations.AlterModelManagers(
            name="instructor",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="password",
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="username",
        ),
    ]
